project:
  type: website

website:
  google-analytics: 375770529
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/noklam
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css



