project:
  type: website

website:
  google-analytics: "G-28PTCJ2ELM"
  title: "blog"
  site-url: https://noklam.github.io/blog
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/noklam
      - icon: twitter
        href: https://twitter.com
      - icon: rss
        href: index.xml
format:
  html:
    theme: cosmo
    css: styles.css



