project:
  type: website

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

website:
  google-analytics: UA-83544344-5
  twitter-card: true
  open-graph: true
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    left:
      - text: "Kedro"
        href: kedro/index.qmd
      - text: "Blog"
        href: blog/index.qmd

  sidebar:
    style: floating

metadata-files: [nbdev.yml, sidebar.yml]